### ISSUE TITLE
Synchronize all report layouts sections connected to the Template (Master Report)

### ISSUE THREAD

**Issue by Annagramm** [RedAndBundle/ForNAVSupport#10]
Hello,

Probably, it would be a good idea, to synchronize changes made in the Master Report (Template) in all the reports that are connected to it. Or add some additional function, so it could be run separately.

Or if it's already exist, could You please clarify how to do that.

**Comment by renebrummel** [comment]
Can you provide some more information? Do you mean things like margins, sections, etc? They need to be set manually on every report. I don't know of a way to make that easier.

If you have any suggestions for ForNAV then please email them to ForNAV directly.

**Comment by Annagramm** [comment]
Thank You for the answer.
Yes, I mean the sections and position of elements in the sections.

For example, if I have template, and use it's section in several reports. 
Then when I change the size of some element, or the content of the element in the template section. 
In the reports that use this template as Master Section, the visual appearence of the template elements will not be updated automatically. 
It's needed to be adjusted on all reports that are using that template manually. So those section will look similar in all reports.
 
Unfortunately, I don't have any suggestions how it could be made. 
But I assume there's already some connection between the template and reports, which used it. So probably it's possible, to update visual appearance of the "template" sections on the related reports.

**Comment by renebrummel** [comment]
I see your point and yes, it could be useful. Unfortunately I don't think it will work, The underlying reports can be completely different, down to the dataitems.

If you are working off a new template your best bet will be to simply copy your template report layout into the child report. Since that does not deal with dataitems and other tech stuff it usually works. But it might not so be careful and back up before you try.
